// src/app/components/layout/Footer.tsx
'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from "next/navigation";


type Link = {
    label: string;
    href: string;
    path?: string;
}

type Service = {
    label: string;
    slug: string;
}

const Footer = () => {
    const router = useRouter();
    const year = new Date().getFullYear();


    function detailsService(Service: Service) {
        router.push(`/services/${Service.slug}`);
    }


    const links: Link[] = [
        { label: "Inicio", href: "#inicio", path: '' },
        { label: "Servicios", href: "#servicios" },
        { label: "Nosotros", href: "#nosotros" },
        { label: "Progreso", href: "#progreso" },
        { label: "Planes", href: "#planes" },
        { label: "Portafolio", href: "#portafolio" },
        { label: "Contacto", href: "#contacto" },
    ];

    const services: Service[] = [
        { label: 'Desarrollo de software a su medida', slug: 'desarrollo-software' },
        { label: 'Desarrollo de apps móviles', slug: 'desarrollo-apps' },
        { label: 'Análisis de datos y visualización', slug: 'analisis-datos' },
        { label: 'Arquitectura y gestión de bases de datos', slug: 'bases-datos' },
        { label: 'Consultoría en transformación digital', slug: 'consultoria-transformacion' },
        { label: 'Diseño UX/UI centrado en el usuario', slug: 'diseno-ux-ui' }
    ]

    return (
        <footer className="w-full bg-[var(--color-primary)] text-[var(--color-light)] relative flex flex-col justify-center pt-10 pb-24 xl:pb-16">
            <div className="w-[90%] mx-auto flex flex-col xl:flex-row gap-10">

                {/* Branding */}
                <div className="flex flex-col gap-4 w-full xl:w-1/4 border-b xl:border-none pb-6">
                    <figure className="flex items-center gap-3 w-fit h-fit">
                        <Image src="/img/logo-white.png" alt="logo-stargrowstudio" width={26} height={26} />
                        <figcaption className="text-white font-semibold text-xl whitespace-nowrap">
                            Star Grow Studio
                        </figcaption>
                    </figure>
                    <p className="text-[.8rem] text-[var(--color-light)] leading-7 max-w-[80%]">
                        Diseñamos y desarrollamos soluciones digitales que impulsan tu crecimiento. Síguenos en nuestras redes sociales y mantente conectado.
                    </p>
                </div>

                {/* Servicios */}
                <div className="flex flex-col gap-3 w-full xl:w-1/4 border-b xl:border-none pb-6">
                    <h3 className="font-bold text-[var(--color-light)]">Servicios</h3>
                    {services.map((service) => (
                        <span onClick={() => detailsService(service)} className="text-sm text-[var(--color-light)] hover:underline cursor-pointer">{service.label}</span>
                    ))}
                </div>

                {/* Enlaces rápidos */}
                <div className="flex flex-col gap-3 w-full xl:w-1/4 border-b xl:border-none pb-6">
                    <h3 className="font-bold text-[var(--color-light)]">Enlaces rápidos</h3>
                    {links.map((link) => (
                        <Link href={link.href} key={link.href} className="text-sm lg:pl-3 font-medium text-[var(--color-light)] hover:underline">-{link.label}</Link>
                    ))}
                </div>

                {/* Contacto */}
                <div className="flex flex-col gap-3 w-full xl:w-1/4 border-b xl:border-none pb-6">
                    <h3 className="font-bold text-[var(--color-light)]">Contacto</h3>
                    <div className="flex items-center gap-3 text-white">
                        <span className="material-symbols-outlined">email</span>
                        <a href="mailto:jstargrowstudio@gmai.com" className="text-sm hover:underline">jstargrowstudio@gmai.com</a>
                    </div>
                    <div className="flex items-center gap-3 text-white">
                        <span className="material-symbols-outlined">phone</span>
                        <a
                            href="https://wa.me/573008236761"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-sm hover:underline">
                            +57 3008236761
                        </a>
                    </div>
                    <div className="flex items-center gap-3 text-white">
                        <span className="material-symbols-outlined">place</span>
                        <a
                            href="https://www.google.com/maps/search/?api=1&query=Calle+27+%7B-05,+Sabanalarga,+Atlántico"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-sm hover:underline">
                            Calle 27 #7B-05
                        </a>
                    </div>
                </div>
            </div>

            {/* Copyright */}
            <div className="w-full bg-[var(--color-secondary)] py-4 absolute bottom-0 left-0">
                <div className="w-[90%] mx-auto flex flex-col xl:flex-row items-center justify-between gap-3">
                    <span className="text-[var(--color-white)] text-center">
                        © {year} StarGrowStudio. Todos los derechos reservados.
                    </span>
                    <div className="flex gap-4">
                        <a href="#" className="text-sm text-[var(--color-light)] hover:underline">Política de privacidad</a>
                        <a href="#" className="text-sm text-[var(--color-light)] hover:underline">Términos de servicio</a>
                    </div>
                </div>
            </div>
        </footer>
    );
};

export default Footer;

// components/Layout/Footer.vue
<template>
  <footer class="footer">
    <div class="footer--inner">
      <div class="footer-branding">
        <figure>
          <img src="../../public/logo-white.png" alt="logo-stargrowstudio" />
          <figcaption>Star Grow Studio</figcaption>
        </figure>
        <p>
          Diseñamos y desarrollamos soluciones digitales que impulsan tu
          crecimiento.Síguenos en nuestras redes sociales y mantente conectado.
        </p>
      </div>
      <div class="footer-services">
        <h3>Servicios</h3>
        <HeaderLink
          label="Desarrollo de software a su medida"
          color="var(--color-light)"
        />
        <HeaderLink
          label="Análisis de datos y visualización"
          color="var(--color-light)"
        />
        <HeaderLink
          label="Arquitectura y gestión de bases de datos"
          color="var(--color-light)"
        />
        <HeaderLink
          label="Consultoría en transformación digital"
          color="var(--color-light)"
        />
        <HeaderLink
          label="Diseño UX/UI centrado en el usuario"
          color="var(--color-light)"
        />
      </div>
      <div class="footer-links">
        <h3>Enlaces rápidos</h3>
        <HeaderLink
          label="Inicio"
          fontWeight="'900'"
          color="var(--color-light)"
          href="#inicio"
        />
        <HeaderLink
          label="Servicios"
          fontWeight="'900'"
          color="var(--color-light)"
          href="#servicios"
        />
        <HeaderLink
          label="Nosotros"
          fontWeight="'900'"
          color="var(--color-light)"
          href="#nosotros"
        />
        <HeaderLink
          label="Progreso"
          fontWeight="'900'"
          color="var(--color-light)"
          href="#progreso"
        />
        <HeaderLink
          label="Portafolio"
          fontWeight="'900'"
          color="var(--color-light)"
        />
        <HeaderLink
          label="Contacto"
          fontWeight="'900'"
          color="var(--cZolor-light)"
        />
      </div>
      
      <div class="footer-contact">
        <h3>Contacto</h3>
        <div class="email">
          <span class="material-symbols-outlined">email</span>
          <HeaderLink label="jstargrowstudio@gmai.com" />
        </div>
        <div class="cellphone">
          <span class="material-symbols-outlined">phone</span>
          <HeaderLink label="+57 3008236761" />
        </div>
        <div class="email">
          <span class="material-symbols-outlined">place</span>
          <HeaderLink label="Calle 27 #7B-05" />
        </div>
      </div>
      <div class="footer-copyright">
        <div class="footer--inner">
          <span> © 2025 StarGrowStudio. Todos los derechos reservados. </span>
          <div class="links">
            <HeaderLink label="Política de privacidad" />
            <HeaderLink label="Términos de servicio" />
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
<script setup>
import HeaderLink from "../UI/headerLink.vue";
</script>
<style>
footer {
  width: 100%;
  min-height: 60vh;
  max-height: fit-content;
  background-color: var(--color-primary);
  display: flex;
  flex-direction: column;
  justify-content: center;
  position: relative;
}

.footer-copyright {
  width: 100%;
  background-color: var(--color-secondary);
  padding-block: 10px;
}

.footer-copyright .footer--inner {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
}

.footer-copyright .footer--inner span {
  color: var(--color-white);
  text-align: center;
}

.footer-copyright .footer--inner .links {
  display: flex;
  align-items: center;
  gap: 15px;
}

.footer .footer-branding,
.footer .footer-links,
.footer .footer-services,
.footer .footer-contact {
  width: 90%;
  margin: 0 auto;
  padding-block: 25px;
  border-bottom: 1px solid var(--color-light);
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 14px;
}

.footer-links > *,
.footer-services > * {
  margin-bottom: 12px;
}

.footer-links,
.footer-services,
.footer-contact h3 {
  color: var(--color-light);
  font-weight: 700;
}

.footer .footer-branding figure {
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  gap: 10px;
}

.footer .footer-branding figure img {
  max-width: 100%;
  height: 100%;
}

.footer .footer-branding figure figcaption {
  color: var(--color-white);
  font-weight: 600;
  white-space: nowrap;
  font-size: 1.4rem;
}

.footer-contact > * {
  display: flex;
  align-items: center;
  gap: 10px;
  color: var(--color-white);
}

.footer .footer-branding p {
  color: var(--color-light);
  max-width: 80%;
  line-height: 28px;
}

@media (min-width: 1280px) {
  .footer .footer--inner {
    width: 90%;
    margin: 0 auto;
    display: flex;
    flex-direction: row;
  }

  .footer--inner .footer-branding,
  .footer--inner .footer-links,
  .footer--inner .footer-services,
  .footer--inner .footer-contact {
    justify-content: start;
    border: none;
  }

  .footer-copyright {
    position: absolute;
    left: 0;
    bottom: 0;
  }

  .footer-copyright .footer--inner {
    flex-direction: row;
    width: 85%;
    justify-content: space-between;
  }
}
</style>
